// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fifaCoinsBestEver;

namespace fifaCoinsBestEver.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("fifaCoinsBestEver.Models.User", b =>
                {
                    b.Property<long>("userId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("modDate");

                    b.Property<string>("pwd");

                    b.Property<int?>("typeValue");

                    b.Property<string>("username");

                    b.HasKey("userId");

                    b.HasIndex("typeValue");

                    b.ToTable("users");
                });

            modelBuilder.Entity("fifaCoinsBestEver.dte.UserRoleType", b =>
                {
                    b.Property<int>("Value")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Value");

                    b.ToTable("UserRoleType");
                });

            modelBuilder.Entity("fifaCoinsBestEver.Models.User", b =>
                {
                    b.HasOne("fifaCoinsBestEver.dte.UserRoleType", "type")
                        .WithMany()
                        .HasForeignKey("typeValue");
                });
#pragma warning restore 612, 618
        }
    }
}
